dbconfig:
  name: "InvestmentHelper"
  collection: "History"
  collectiontest: "TestCollection"
  server: "mongodb://127.0.0.1:27017" #localmongo
  #dbserver: "mongodb://mongodb:27017" #docker

ventagekey: "RFQVPDIH6W9SQV2O"

localport: "8090"

