dbconfig:
  name: "InvestmentHelper"
  collection: "History"
  collectiontest: "TestCollection"
  server: "mongodb://127.0.0.1:27017"

ventagekey: "RFQVPDIH6W9SQV2O"

ventagekeytest: "FUSAUHUZ3W0NG9V0"

pageserver: "http://localhost:63343"

localport: "8090"

